import type { Metadata } from "next";
import { Noto_Sans_Thai } from "next/font/google";
import "./globals.css";
import { AppSidebar } from "@/components/app-sidebar";
import { SiteHeader } from "@/components/site-header";
import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";
import { TooltipProvider } from "@/components/ui/tooltip";

const notoSansThai = Noto_Sans_Thai({
	variable: "--font-noto-sans-thai",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="th">
			<body
				className={`${notoSansThai.variable} antialiased`}
			>
				<TooltipProvider>
					<SidebarProvider
						style={
							{
								"--sidebar-width": "calc(var(--spacing) * 72)",
								"--header-height": "calc(var(--spacing) * 12)",
							} as React.CSSProperties
						}
					>
						<AppSidebar variant="inset" />
						<SidebarInset>
							<SiteHeader />
							<div className="@container/main flex flex-1 flex-col p-4 gap-4 md:gap-6 md:p-6">
								{children}
							</div>
						</SidebarInset>
					</SidebarProvider>
				</TooltipProvider>
			</body>
		</html>
	);
}
